[build]
  base = "."
  publish = "frontend/build"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://karno-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
