services:
  - type: web
    name: karno-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
